### ISSUE TITLE
Any field of view greater than 180° fails to render properly

### ISSUE THREAD

**Issue by richardwilkes** [legends2k/2d-fov#3] opened 2023-08-08 00:14 UTC
Not sure if you're actually interested in this anymore, but thought I'd bring it up just in case. I'm actually trying to do something similar to what you already have, but with a full 360° range. I could use your code directly and just run it twice for those cases where the total FoV is greater than 180° (splitting the range between the two runs) and union the polygons, but that's likely way more inefficient than it could be with a real solution.

**Comment by legends2k** [comment] 2023-10-12 15:10
Sorry, I've to close this a by design, as my original design is to have a vision cone / sector < 180°.  If you could contribute an implementation I'd be happy to re-open this and review your PR.

**Closed as not planned by legends2k** 2023-10-12 15:10 UTC
